### ISSUE TITLE
🐞[ BUG ] Postman은 작동하지만 Swagger는 작동하지 않음

### ISSUE THREAD

**Issue by DDonghyeo** [WaitherTeam/Waither-BE#92]
Swagger API Docs 배포 후, user-service의 회원가입 로직을 테스트하는 중에 발생했습니다.

## - Swagger

![image](https://github.com/WaitherTeam/Waither-BE/assets/98632435/d05327a5-e9e0-4451-82a4-bef1fa301d40)
![image](https://github.com/WaitherTeam/Waither-BE/assets/98632435/dc7305f3-0482-4382-a12f-b4d21f76a7d9)
![image](https://github.com/WaitherTeam/Waither-BE/assets/98632435/f7083fb6-429d-4b97-a88a-00bbb31d0c61)

Swagger는 403 Forbidden을 Return합니다.

## - Postman
![image](https://github.com/WaitherTeam/Waither-BE/assets/98632435/81dffd2e-8091-4ae9-912a-5667e1329a96)

Postman의 같은 요청은 정상적으로 작동합니다.

## - Settings
apiGateway의 설정 중 일부
![image](https://github.com/WaitherTeam/Waither-BE/assets/98632435/a661cde3-a791-48af-ae72-5787acbfcd73)

Gateway 로그
![image](https://github.com/WaitherTeam/Waither-BE/assets/98632435/b8624ce9-cd49-4df5-b16e-ee5b60f0ccf4)

처음 겪는 버그인데, 도무지 어떤 이유인지 모르겠네요. 혹시 아시는 분 있을까요?

**Comment by yeopyeop-82** [comment]
일단 제가 유엠씨 프로젝트했을때 정확히 같은 문제 겪은적이 있었는데 .. 스웨거 관련 설정 다 밀어버리고 다시 하니까 되긴 되었습니다! 관련 이슈 저희 프로젝트에서 찾아서 링크 드릴게요 !

**Comment by seheonnn** [comment]
```
@Configuration
public class SwaggerConfig {
	// url : http://localhost:8080/swagger-ui/index.html#/
	private static final String SECURITY_SCHEME_NAME = "bearerAuth";

	@Bean
	public OpenAPI api() {
		Server server = new Server().url("/");

		return new OpenAPI()
			.addSecurityItem(new SecurityRequirement().addList(SECURITY_SCHEME_NAME))
			.components(authSetting())
			.info(getSwaggerInfo())
			.addServersItem(server);
	}

	private Info getSwaggerInfo() {
		License license = new License();
		license.setName("{Application}");

		return new Info()
			.title("Spon-Us API Document")
			.description("Spon-Us의 API 문서 입니다.")
			.version("v0.0.1")
			.license(license);
	}

	private Components authSetting() {

		return new Components()
			.addSecuritySchemes(SECURITY_SCHEME_NAME,
				new SecurityScheme()
					.name(SECURITY_SCHEME_NAME)
					.type(SecurityScheme.Type.HTTP)
					.scheme("bearer")
					.bearerFormat("JWT"));
	}
}
```

**Comment by DDonghyeo** [comment]
해결했습니다. 결론은 CORS 오류였습니다.

개발자 모드에서 CORS Error로 나오지 않아서 CORS가 아닌 줄 알았는데..

https://velog.io/@mingeloper/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-403%EC%97%90%EB%9F%AC-TroubleShootingFeat-CORS-Swagger#6-%EB%93%9C%EB%94%94%EC%96%B4-%EC%9E%A1%EC%95%98%EB%8B%A4

위 글을 보고 참고했습니다.

해결한 commit : 4b1d0588ef0d1b4a9c73a080abeb14160d939308

**Comment by DDonghyeo** [comment]
추가로 알게된 내용을 블로그 글에 정리했습니다.

https://ddonghyeo.tistory.com/58#2.%20%ED%95%B4%EA%B2%B0-1
